// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft_WebSite.DataAccess;

#nullable disable

namespace Microsoft_WebSite.DataAccess.Migrations
{
    [DbContext(typeof(Microsoft_Website_Context))]
    [Migration("20250209074107_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft_WebSite.DataAccess.Entities.AboutUs", b =>
                {
                    b.Property<int>("AboutUsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutUsID"));

                    b.Property<string>("AboutUsContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutUsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutUsID");

                    b.ToTable("AboutUsTable");
                });

            modelBuilder.Entity("Microsoft_WebSite.DataAccess.Entities.ContactUs", b =>
                {
                    b.Property<int>("ContactUsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactUsID"));

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactUsID");

                    b.ToTable("ContactUsTable");
                });

            modelBuilder.Entity("Microsoft_WebSite.DataAccess.Entities.Package", b =>
                {
                    b.Property<int>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageID"));

                    b.Property<string>("PackageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageID");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageID = 1,
                            PackageContent = "Free Plan",
                            PackageTitle = "Free"
                        },
                        new
                        {
                            PackageID = 2,
                            PackageContent = "Pro Plan",
                            PackageTitle = "Pro"
                        },
                        new
                        {
                            PackageID = 3,
                            PackageContent = "Enterprise Plan",
                            PackageTitle = "Enterprise"
                        });
                });

            modelBuilder.Entity("Microsoft_WebSite.DataAccess.Entities.PackageFeature", b =>
                {
                    b.Property<int>("PackageFeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageFeatureID"));

                    b.Property<string>("PackageFeatureTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageFeatureID");

                    b.ToTable("PackageFeatures");

                    b.HasData(
                        new
                        {
                            PackageFeatureID = 1,
                            PackageFeatureTitle = "Public"
                        },
                        new
                        {
                            PackageFeatureID = 2,
                            PackageFeatureTitle = "Private"
                        },
                        new
                        {
                            PackageFeatureID = 3,
                            PackageFeatureTitle = "Permissions"
                        },
                        new
                        {
                            PackageFeatureID = 4,
                            PackageFeatureTitle = "Sharing"
                        },
                        new
                        {
                            PackageFeatureID = 5,
                            PackageFeatureTitle = "Unlimited members"
                        },
                        new
                        {
                            PackageFeatureID = 6,
                            PackageFeatureTitle = "Extra security"
                        });
                });

            modelBuilder.Entity("Microsoft_WebSite.DataAccess.Entities.PackageProductUnit", b =>
                {
                    b.Property<int>("PackageProductUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageProductUnitID"));

                    b.Property<string>("PackageProductUnitContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageProductUnitPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageProductUnitTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageProductUnitID");

                    b.ToTable("PackageProductUnits");

                    b.HasData(
                        new
                        {
                            PackageProductUnitID = 1,
                            PackageProductUnitContent = "10 users included",
                            PackageProductUnitPrice = "100",
                            PackageProductUnitTitle = "users included"
                        },
                        new
                        {
                            PackageProductUnitID = 2,
                            PackageProductUnitContent = "2 GB of storage",
                            PackageProductUnitPrice = "10",
                            PackageProductUnitTitle = "GB of storage"
                        });
                });

            modelBuilder.Entity("Microsoft_WebSite.DataAccess.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("ServiceContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Microsoft_WebSite.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            UserEmail = "trkhamarat@gmail.com",
                            UserPassword = "123456",
                            UserUsername = "trkhamarat",
                            userRole = "Admin"
                        });
                });

            modelBuilder.Entity("PackagePackageFeature", b =>
                {
                    b.Property<int>("PackageFeaturesPackageFeatureID")
                        .HasColumnType("int");

                    b.Property<int>("PackagesPackageID")
                        .HasColumnType("int");

                    b.HasKey("PackageFeaturesPackageFeatureID", "PackagesPackageID");

                    b.HasIndex("PackagesPackageID");

                    b.ToTable("PackagePackageFeature");
                });

            modelBuilder.Entity("PackagePackageProductUnit", b =>
                {
                    b.Property<int>("PackageProductUnitsPackageProductUnitID")
                        .HasColumnType("int");

                    b.Property<int>("PackagesPackageID")
                        .HasColumnType("int");

                    b.HasKey("PackageProductUnitsPackageProductUnitID", "PackagesPackageID");

                    b.HasIndex("PackagesPackageID");

                    b.ToTable("PackagePackageProductUnit");
                });

            modelBuilder.Entity("PackagePackageFeature", b =>
                {
                    b.HasOne("Microsoft_WebSite.DataAccess.Entities.PackageFeature", null)
                        .WithMany()
                        .HasForeignKey("PackageFeaturesPackageFeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft_WebSite.DataAccess.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackagePackageProductUnit", b =>
                {
                    b.HasOne("Microsoft_WebSite.DataAccess.Entities.PackageProductUnit", null)
                        .WithMany()
                        .HasForeignKey("PackageProductUnitsPackageProductUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft_WebSite.DataAccess.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
